### ISSUE TITLE
Mark as done and mark as important Bug

### ISSUE THREAD

**Issue by jponte99** [Sofia-Machado/todolist#2]
First click on a task item (over the "done" or "important" icons) don't execute the event (for example, mark as done). It only execute it on the 2nd click.

However first click on Delete icon appears to work as expected.

**Comment by Sofia-Machado** [comment]
Had to change the object diectly because useState is asynchronous.
Changed it from:
```
setimportant(prevState => !prevState);
patch(`tasks/${task.id}`, {important: important})
```
to:
```
let importantNew = !task.important;
patch(`tasks/${task.id}`, {important: importantNew})
```
