### ISSUE TITLE
Confirm box on Delete

### ISSUE THREAD

**Issue by jponte99** [Sofia-Machado/todolist#3]
Before deleting, it should ask if we are sure, using a MUI confirm box of course :)
Also, it should display a message "The task xyz has been deleted" on the top or bottom of the page (or anywhere else). This message will disappear automatically after x seconds (also using MU... I think there is a control for this).

Note: In production mode, a better alternative would be to delete without confirm but showing an "Undo" message during x seconds. But in this case, it's not necessary.

**Comment by Sofia-Machado** [comment]
Added a collapse alert with material ui
